<h1 align = center>Numpy Library

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-the-library" data-toc-modified-id="Import-the-library-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import the library</a></span></li><li><span><a href="#Trigonometric-functions-" data-toc-modified-id="Trigonometric-functions--2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Trigonometric functions </a></span></li><li><span><a href="#Round-Function" data-toc-modified-id="Round-Function-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Round Function</a></span></li><li><span><a href="#Ceil-&amp;-Floor-functions" data-toc-modified-id="Ceil-&amp;-Floor-functions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Ceil &amp; Floor functions</a></span></li><li><span><a href="#mod-&amp;-power-functions" data-toc-modified-id="mod-&amp;-power-functions-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>mod &amp; power functions</a></span></li><li><span><a href="#Matrices" data-toc-modified-id="Matrices-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Matrices</a></span><ul class="toc-item"><li><span><a href="#Manual-Matrix-using-format-command-" data-toc-modified-id="Manual-Matrix-using-format-command--6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Manual Matrix using format command </a></span></li><li><span><a href="#1-D-Matrix-" data-toc-modified-id="1-D-Matrix--6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>1 D Matrix </a></span></li><li><span><a href="#2-D-Matrix-" data-toc-modified-id="2-D-Matrix--6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>2 D Matrix </a></span></li><li><span><a href="#Matrix-using-range-function-" data-toc-modified-id="Matrix-using-range-function--6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Matrix using range function </a></span></li><li><span><a href="#Empty-Matrix" data-toc-modified-id="Empty-Matrix-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Empty Matrix</a></span></li><li><span><a href="#Get-a-Random-value" data-toc-modified-id="Get-a-Random-value-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Get a Random value</a></span><ul class="toc-item"><li><span><a href="#-uniform-function-" data-toc-modified-id="-uniform-function--6.6.1"><span class="toc-item-num">6.6.1&nbsp;&nbsp;</span> uniform function </a></span></li><li><span><a href="#-rand-function-" data-toc-modified-id="-rand-function--6.6.2"><span class="toc-item-num">6.6.2&nbsp;&nbsp;</span> rand function </a></span></li></ul></li><li><span><a href="#Get-a-Random-Matrix" data-toc-modified-id="Get-a-Random-Matrix-6.7"><span class="toc-item-num">6.7&nbsp;&nbsp;</span>Get a Random Matrix</a></span><ul class="toc-item"><li><span><a href="#option-(1)" data-toc-modified-id="option-(1)-6.7.1"><span class="toc-item-num">6.7.1&nbsp;&nbsp;</span>option (1)</a></span></li><li><span><a href="#option-(2)" data-toc-modified-id="option-(2)-6.7.2"><span class="toc-item-num">6.7.2&nbsp;&nbsp;</span>option (2)</a></span></li><li><span><a href="#option-(3)" data-toc-modified-id="option-(3)-6.7.3"><span class="toc-item-num">6.7.3&nbsp;&nbsp;</span>option (3)</a></span></li><li><span><a href="#option-(4)" data-toc-modified-id="option-(4)-6.7.4"><span class="toc-item-num">6.7.4&nbsp;&nbsp;</span>option (4)</a></span></li><li><span><a href="#option-(5)" data-toc-modified-id="option-(5)-6.7.5"><span class="toc-item-num">6.7.5&nbsp;&nbsp;</span>option (5)</a></span></li><li><span><a href="#option-(6)" data-toc-modified-id="option-(6)-6.7.6"><span class="toc-item-num">6.7.6&nbsp;&nbsp;</span>option (6)</a></span></li></ul></li><li><span><a href="#-Random-normal-function" data-toc-modified-id="-Random-normal-function-6.8"><span class="toc-item-num">6.8&nbsp;&nbsp;</span> Random normal function</a></span></li><li><span><a href="#Get-a-Random-value-within-a-certain-range-(randint-function)" data-toc-modified-id="Get-a-Random-value-within-a-certain-range-(randint-function)-6.9"><span class="toc-item-num">6.9&nbsp;&nbsp;</span>Get a Random value within a certain range (randint function)</a></span></li><li><span><a href="#choice-function" data-toc-modified-id="choice-function-6.10"><span class="toc-item-num">6.10&nbsp;&nbsp;</span>choice function</a></span><ul class="toc-item"><li><span><a href="#option-(1)" data-toc-modified-id="option-(1)-6.10.1"><span class="toc-item-num">6.10.1&nbsp;&nbsp;</span>option (1)</a></span></li><li><span><a href="#option-(2)" data-toc-modified-id="option-(2)-6.10.2"><span class="toc-item-num">6.10.2&nbsp;&nbsp;</span>option (2)</a></span></li></ul></li><li><span><a href="#shuffle-function" data-toc-modified-id="shuffle-function-6.11"><span class="toc-item-num">6.11&nbsp;&nbsp;</span>shuffle function</a></span></li><li><span><a href="#Matrix-of-zeros-or-ones" data-toc-modified-id="Matrix-of-zeros-or-ones-6.12"><span class="toc-item-num">6.12&nbsp;&nbsp;</span>Matrix of zeros or ones</a></span><ul class="toc-item"><li><span><a href="#1-D" data-toc-modified-id="1-D-6.12.1"><span class="toc-item-num">6.12.1&nbsp;&nbsp;</span>1 D</a></span></li><li><span><a href="#2-D" data-toc-modified-id="2-D-6.12.2"><span class="toc-item-num">6.12.2&nbsp;&nbsp;</span>2 D</a></span></li><li><span><a href="#3-D" data-toc-modified-id="3-D-6.12.3"><span class="toc-item-num">6.12.3&nbsp;&nbsp;</span>3 D</a></span></li></ul></li><li><span><a href="#Identity-Matrix" data-toc-modified-id="Identity-Matrix-6.13"><span class="toc-item-num">6.13&nbsp;&nbsp;</span>Identity Matrix</a></span></li><li><span><a href="#full-Matrix" data-toc-modified-id="full-Matrix-6.14"><span class="toc-item-num">6.14&nbsp;&nbsp;</span>full Matrix</a></span></li><li><span><a href="#range-Matrix" data-toc-modified-id="range-Matrix-6.15"><span class="toc-item-num">6.15&nbsp;&nbsp;</span>range Matrix</a></span></li><li><span><a href="#linspace-command" data-toc-modified-id="linspace-command-6.16"><span class="toc-item-num">6.16&nbsp;&nbsp;</span>linspace command</a></span></li><li><span><a href="#lincpace-to-a-Matrix" data-toc-modified-id="lincpace-to-a-Matrix-6.17"><span class="toc-item-num">6.17&nbsp;&nbsp;</span>lincpace to a Matrix</a></span></li><li><span><a href="#Diagonal-Matrix" data-toc-modified-id="Diagonal-Matrix-6.18"><span class="toc-item-num">6.18&nbsp;&nbsp;</span>Diagonal Matrix</a></span></li><li><span><a href="#Dealing-with-Matrices" data-toc-modified-id="Dealing-with-Matrices-6.19"><span class="toc-item-num">6.19&nbsp;&nbsp;</span>Dealing with Matrices</a></span></li><li><span><a href="#Compare-between-Matrices" data-toc-modified-id="Compare-between-Matrices-6.20"><span class="toc-item-num">6.20&nbsp;&nbsp;</span>Compare between Matrices</a></span></li><li><span><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-6.21"><span class="toc-item-num">6.21&nbsp;&nbsp;</span>Matrix multiplication</a></span></li><li><span><a href="#matrix-summation-value" data-toc-modified-id="matrix-summation-value-6.22"><span class="toc-item-num">6.22&nbsp;&nbsp;</span>matrix summation value</a></span></li><li><span><a href="#matrix-length" data-toc-modified-id="matrix-length-6.23"><span class="toc-item-num">6.23&nbsp;&nbsp;</span>matrix length</a></span></li><li><span><a href="#Matrix-Dimension" data-toc-modified-id="Matrix-Dimension-6.24"><span class="toc-item-num">6.24&nbsp;&nbsp;</span>Matrix Dimension</a></span></li><li><span><a href="#data-type-inside-the-Matrix" data-toc-modified-id="data-type-inside-the-Matrix-6.25"><span class="toc-item-num">6.25&nbsp;&nbsp;</span>data type inside the Matrix</a></span></li><li><span><a href="#The-sum-of-the-matrix-diagonal" data-toc-modified-id="The-sum-of-the-matrix-diagonal-6.26"><span class="toc-item-num">6.26&nbsp;&nbsp;</span>The sum of the matrix diagonal</a></span></li><li><span><a href="#Subtraction-From-The-Matrix" data-toc-modified-id="Subtraction-From-The-Matrix-6.27"><span class="toc-item-num">6.27&nbsp;&nbsp;</span>Subtraction From The Matrix</a></span></li><li><span><a href="#Modify-Values" data-toc-modified-id="Modify-Values-6.28"><span class="toc-item-num">6.28&nbsp;&nbsp;</span>Modify Values</a></span></li><li><span><a href="#Dealing-with-copied-matrices-" data-toc-modified-id="Dealing-with-copied-matrices--6.29"><span class="toc-item-num">6.29&nbsp;&nbsp;</span>Dealing with copied matrices </a></span></li><li><span><a href="#Independent-Matrices-" data-toc-modified-id="Independent-Matrices--6.30"><span class="toc-item-num">6.30&nbsp;&nbsp;</span>Independent Matrices </a></span></li><li><span><a href="#Split-command" data-toc-modified-id="Split-command-6.31"><span class="toc-item-num">6.31&nbsp;&nbsp;</span>Split command</a></span></li><li><span><a href="#Select-an-Item-form-the-matrix" data-toc-modified-id="Select-an-Item-form-the-matrix-6.32"><span class="toc-item-num">6.32&nbsp;&nbsp;</span>Select an Item form the matrix</a></span></li><li><span><a href="#Combine-Matrices" data-toc-modified-id="Combine-Matrices-6.33"><span class="toc-item-num">6.33&nbsp;&nbsp;</span>Combine Matrices</a></span><ul class="toc-item"><li><span><a href="#stack-command" data-toc-modified-id="stack-command-6.33.1"><span class="toc-item-num">6.33.1&nbsp;&nbsp;</span>stack command</a></span></li><li><span><a href="#Concatenate-command" data-toc-modified-id="Concatenate-command-6.33.2"><span class="toc-item-num">6.33.2&nbsp;&nbsp;</span>Concatenate command</a></span></li></ul></li><li><span><a href="#Find-the-Matrix-Variance-and-the-Covariance-" data-toc-modified-id="Find-the-Matrix-Variance-and-the-Covariance--6.34"><span class="toc-item-num">6.34&nbsp;&nbsp;</span>Find the Matrix Variance and the Covariance </a></span></li><li><span><a href="#Mathematical-Operations-for-Matrices" data-toc-modified-id="Mathematical-Operations-for-Matrices-6.35"><span class="toc-item-num">6.35&nbsp;&nbsp;</span>Mathematical Operations for Matrices</a></span><ul class="toc-item"><li><span><a href="#Addition-and-Subtraction--" data-toc-modified-id="Addition-and-Subtraction---6.35.1"><span class="toc-item-num">6.35.1&nbsp;&nbsp;</span>Addition and Subtraction  </a></span></li><li><span><a href="#Multiplication-and-division" data-toc-modified-id="Multiplication-and-division-6.35.2"><span class="toc-item-num">6.35.2&nbsp;&nbsp;</span>Multiplication and division</a></span></li><li><span><a href="#Multiplication-and-division-by-a-number" data-toc-modified-id="Multiplication-and-division-by-a-number-6.35.3"><span class="toc-item-num">6.35.3&nbsp;&nbsp;</span>Multiplication and division by a number</a></span></li><li><span><a href="#functions-of-the-matrix" data-toc-modified-id="functions-of-the-matrix-6.35.4"><span class="toc-item-num">6.35.4&nbsp;&nbsp;</span>functions of the matrix</a></span></li><li><span><a href="#Multiply-the-Matrices" data-toc-modified-id="Multiply-the-Matrices-6.35.5"><span class="toc-item-num">6.35.5&nbsp;&nbsp;</span>Multiply the Matrices</a></span></li><li><span><a href="#Matrix-Summation" data-toc-modified-id="Matrix-Summation-6.35.6"><span class="toc-item-num">6.35.6&nbsp;&nbsp;</span>Matrix Summation</a></span></li><li><span><a href="#Statistical-Values" data-toc-modified-id="Statistical-Values-6.35.7"><span class="toc-item-num">6.35.7&nbsp;&nbsp;</span>Statistical Values</a></span></li><li><span><a href="#Correlation-Coefficient" data-toc-modified-id="Correlation-Coefficient-6.35.8"><span class="toc-item-num">6.35.8&nbsp;&nbsp;</span>Correlation Coefficient</a></span></li><li><span><a href="#Matrix-sort" data-toc-modified-id="Matrix-sort-6.35.9"><span class="toc-item-num">6.35.9&nbsp;&nbsp;</span>Matrix sort</a></span></li><li><span><a href="#Matrix-Inversion" data-toc-modified-id="Matrix-Inversion-6.35.10"><span class="toc-item-num">6.35.10&nbsp;&nbsp;</span>Matrix Inversion</a></span></li></ul></li></ul></li><li><span><a href="#-Read-files" data-toc-modified-id="-Read-files-7"><span class="toc-item-num">7&nbsp;&nbsp;</span> Read files</a></span><ul class="toc-item"><li><span><a href="#Load-and-read-the-files" data-toc-modified-id="Load-and-read-the-files-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Load and read the files</a></span><ul class="toc-item"><li><span><a href="#Example-(1):" data-toc-modified-id="Example-(1):-7.1.1"><span class="toc-item-num">7.1.1&nbsp;&nbsp;</span>Example (1):</a></span></li><li><span><a href="#Example-(2):" data-toc-modified-id="Example-(2):-7.1.2"><span class="toc-item-num">7.1.2&nbsp;&nbsp;</span>Example (2):</a></span></li><li><span><a href="#Example-(3):" data-toc-modified-id="Example-(3):-7.1.3"><span class="toc-item-num">7.1.3&nbsp;&nbsp;</span>Example (3):</a></span></li></ul></li></ul></li><li><span><a href="#Polynomials" data-toc-modified-id="Polynomials-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Polynomials</a></span><ul class="toc-item"><li><span><a href="#polyfit-command" data-toc-modified-id="polyfit-command-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>polyfit command</a></span></li><li><span><a href="#Get-the-Polynomial-Equation-" data-toc-modified-id="Get-the-Polynomial-Equation--8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Get the Polynomial Equation </a></span></li><li><span><a href="#Compansate-The-Value-of-&quot;x&quot;" data-toc-modified-id="Compansate-The-Value-of-&quot;x&quot;-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Compansate The Value of "x"</a></span><ul class="toc-item"><li><span><a href="#Option-(1):" data-toc-modified-id="Option-(1):-8.3.1"><span class="toc-item-num">8.3.1&nbsp;&nbsp;</span>Option (1):</a></span></li><li><span><a href="#Option-(2):" data-toc-modified-id="Option-(2):-8.3.2"><span class="toc-item-num">8.3.2&nbsp;&nbsp;</span>Option (2):</a></span></li></ul></li><li><span><a href="#Derivative" data-toc-modified-id="Derivative-8.4"><span class="toc-item-num">8.4&nbsp;&nbsp;</span>Derivative</a></span><ul class="toc-item"><li><span><a href="#polyder-command" data-toc-modified-id="polyder-command-8.4.1"><span class="toc-item-num">8.4.1&nbsp;&nbsp;</span>polyder command</a></span></li><li><span><a href="#Compansate-the-value-of-&quot;x&quot;" data-toc-modified-id="Compansate-the-value-of-&quot;x&quot;-8.4.2"><span class="toc-item-num">8.4.2&nbsp;&nbsp;</span>Compansate the value of "x"</a></span></li></ul></li><li><span><a href="#Integration" data-toc-modified-id="Integration-8.5"><span class="toc-item-num">8.5&nbsp;&nbsp;</span>Integration</a></span><ul class="toc-item"><li><span><a href="#polyint-command" data-toc-modified-id="polyint-command-8.5.1"><span class="toc-item-num">8.5.1&nbsp;&nbsp;</span>polyint command</a></span></li><li><span><a href="#Compansate-the-Value-of-&quot;x&quot;" data-toc-modified-id="Compansate-the-Value-of-&quot;x&quot;-8.5.2"><span class="toc-item-num">8.5.2&nbsp;&nbsp;</span>Compansate the Value of "x"</a></span></li></ul></li><li><span><a href="#Roots-of-the-Equation" data-toc-modified-id="Roots-of-the-Equation-8.6"><span class="toc-item-num">8.6&nbsp;&nbsp;</span>Roots of the Equation</a></span></li></ul></li><li><span><a href="#Deal-with-time" data-toc-modified-id="Deal-with-time-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Deal with time</a></span><ul class="toc-item"><li><span><a href="#Datetime64-command" data-toc-modified-id="Datetime64-command-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Datetime64 command</a></span></li><li><span><a href="#Days-Increase" data-toc-modified-id="Days-Increase-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Days Increase</a></span></li><li><span><a href="#Days-Decrease" data-toc-modified-id="Days-Decrease-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Days Decrease</a></span></li><li><span><a href="#Days-Difference" data-toc-modified-id="Days-Difference-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>Days Difference</a></span></li></ul></li><li><span><a href="#functions-in-numpy" data-toc-modified-id="functions-in-numpy-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>functions in numpy</a></span></li></ul></div>

<h2 align=left>Import the library

In [1]:
from  numpy import *

<h2 align=left>Trigonometric functions 

In [2]:
# The problem with trigonometric functions is that they deal with radians in python, not degrees

a = sin(30)
b = cos(30)
c = tan(30)

print(a , b , c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [3]:
# To remedy the matter, the number is multiplied by (pi / 180).

a = sin(30*pi/180)
b = cos(30*pi/180)
c = tan(30*pi/180)

print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [4]:
# Or use the deg2rad function 

a = sin(deg2rad(30))
b = cos(deg2rad(30))
c = tan(deg2rad(30))

print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


<h2 align=left>Round Function

In [5]:
# round command  

a = round(3.68528)
b = round(3.68528,1) # round the number to the first decimal number 
c = round(3.68528,2) # round the number to the second decimal number 
d = round(3.68528,3) # round the number to the third decimal number
e = round(3.68528,4) # round the number to the forth decimal number

print(a)
print(b)
print(c)
print(d)
print(e)

4
3.7
3.69
3.685
3.6853


<h2 align=left>Ceil & Floor functions

In [6]:
# ceil, floor commands for higher and lower approximation.  

a = floor(3.68528)
b = ceil(3.68528)

print(a)
print(b)

3.0
4.0


<h2 align=left>mod & power functions

In [7]:
a = mod(20,7) # the remaining of the division (20/7 = 2.8571), (20-(2*7) = 6)
b = power(2,5)

print(a)
print(b)

6
32


<h2 align=left>Matrices

<h3 align=left>Manual Matrix using format command 

In [8]:
# We can create the matrix using format command 

a = matrix('{} {} ; {} {}'.format(1,2,3,4))
b = matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6))

print('a =', a)
print('-------------------------')
print('b =', b)

a = [[1 2]
 [3 4]]
-------------------------
b = [[1 2 3]
 [4 5 6]]


<h3 align=left>1 D Matrix 

In [9]:
# The array command is used to convert a list into an array

a = [2,3,6,5,4,7,8] # list
b = array(a)        # array

print(a)
print('-------------------------')
print(b)

[2, 3, 6, 5, 4, 7, 8]
-------------------------
[2 3 6 5 4 7 8]


<h3 align=left>2 D Matrix 

In [10]:
# Also a two-dimensional matrix can be made 

a = [[1,2,3],[5,3,6],[9,6,5]]
b = array(a)

print('a = ', a)
print('-------------------------')
print('b = ', b)

a =  [[1, 2, 3], [5, 3, 6], [9, 6, 5]]
-------------------------
b =  [[1 2 3]
 [5 3 6]
 [9 6 5]]


<h3 align=left>Matrix using range function 

In [11]:
# The range command can be used to create an array

a = array([range(i, i + 3) for i in [2, 4, 6]])
print(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [12]:
# •	Variables can be declared after they are written

a = array([('x', 3, 4.2), ('y', 4, 5.3), ('z', 5, 6.3)],
          dtype=[('name', 'U5'), ('number', 'i2'),
                 ('value', 'f4')])
''' where 
* U5 represents: the number of the string letters (maximum 5)
* i2 : the number of int. value( maximum 2)
* f4 : the number of float value ( maximum 4)
'''

print(a)

[('x', 3, 4.2) ('y', 4, 5.3) ('z', 5, 6.3)]


<h3 align=left>Empty Matrix

In [13]:
# Using the empty command, an empty array or matrix can be created  

a = empty ((2,3))
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.22646744e-307 9.45763339e-308 4.00535703e-307]]


<h3 align=left>Get a Random value

<h4 align=left> uniform function 

In [14]:
# The uniform command returns a random value

a = random.uniform(1,10)     # one random value from 1 to 10
b = random.uniform(1,10,20)  # 20 random values from 1 to 10

print(a)
print('-------------------------')
print(b)
print('-------------------------')

8.781908980241365
-------------------------
[2.23125023 1.63702357 6.46737668 5.622309   7.04186187 6.83114168
 7.86958179 9.41997854 1.78779309 5.87743983 8.52898432 3.68823673
 5.75740564 1.49986004 8.96774077 5.21110581 5.61297214 9.53194691
 2.93585773 5.47632354]
-------------------------


<h4 align=left> rand function 

In [15]:
# Here, Using rand command helps to get random numbers from 0 to 1 are used  

a = random.rand(15) 
print(a)

[0.25989335 0.79683331 0.77765412 0.92616414 0.78644668 0.5070631
 0.03918235 0.21700498 0.31290231 0.71761638 0.44264464 0.78881047
 0.97184017 0.87144546 0.58322638]


<h3 align=left>Get a Random Matrix

<h4 align=left>option (1)

In [16]:
# The random.random command can create an array with random numbers between 0 and 1   

a = random.random((2,3))
print(a)

[[0.82769349 0.39292491 0.17863016]
 [0.73157698 0.0979619  0.59458029]]


<h4 align=left>option (2)

In [17]:
# An array of integers can be made between 0 and 10 using randint command  

a = random.randint(0, 10, (3, 3))

'''where
0 & 10 is the range
3,3 is the matrix size'''

print(a)

[[5 9 3]
 [4 3 9]
 [7 1 5]]


<h4 align=left>option (3)

In [18]:
# or three dimensions  

a = random.randint(5,10, size=(3, 2, 5))

'''where
5, 10 is the numbers range
3 the dimensions numbers
2 is the raws numbers
5 is the columns numbers'''
print(a)

[[[5 6 7 9 8]
  [6 9 7 5 5]]

 [[8 8 5 8 9]
  [5 5 6 8 5]]

 [[5 6 7 6 6]
  [9 7 6 9 5]]]


<h4 align=left>option (4)

In [19]:
# Or use a row of numbers and form it 

a = random.randint(1,60,25)
b = reshape(a,(5,5))

print(a)
print(b)

[52 29 21 36 11 29 31 56 45 47 37 56  1 23 28 20 43 25 18 39 17 48 53 12
 51]
[[52 29 21 36 11]
 [29 31 56 45 47]
 [37 56  1 23 28]
 [20 43 25 18 39]
 [17 48 53 12 51]]


<h4 align=left>option (5)

In [20]:
# or a two-dimensional matrix between 0 & 1

a = random.rand(5,3)
print(a)

[[0.76350622 0.58435628 0.97827138]
 [0.67697192 0.83985071 0.12705612]
 [0.93476594 0.47137008 0.67139969]
 [0.64985367 0.25244755 0.72079362]
 [0.38902194 0.77980449 0.16444589]]


<h4 align=left>option (6)

In [21]:
# or a three-dimensional matrix   

a = random.rand(4,3,2)
print(a)

[[[0.29187914 0.89761121]
  [0.46182751 0.13981212]
  [0.7746511  0.44460625]]

 [[0.29768992 0.403605  ]
  [0.26974129 0.86855743]
  [0.2731609  0.84139574]]

 [[0.52556495 0.38882235]
  [0.62458009 0.93532229]
  [0.52239929 0.15004205]]

 [[0.30349926 0.83798858]
  [0.0649942  0.26831448]
  [0.91870625 0.45099549]]]


<h3 align=left> Random normal function

In [22]:
# The random.normal command brings the normal distribution of numbers between zero and 1 as a Gaussian distribution.    

a = random.normal(0,1,10)  #  get 10 numbers within range 0 & 1.
print(a)

[-0.4546004  -0.31247463  0.81958729  0.51559646  0.29258305 -0.26250391
 -0.08085571  0.18017785  1.57623717  0.74889128]


<h3 align=left>Get a Random value within a certain range (randint function)

In [23]:
# The random.randint command can specify an integer random number between a certain range of two numbers 

a = random.randint(150) # get random numbers between 0 & 150
print(a)

19


In [24]:
# You can select certain numbers of random integers within a range

a =random.randint(5, size=7)
print(a)

[0 0 1 2 4 1 2]


In [25]:
# If two numbers are written, then the numbers range between the two numbers  

a =random.randint(5,20, size=3)
print(a)

[18 11  7]


<h3 align=left>choice function

<h4 align=left>option (1)

In [26]:
# The choice command selects a random value a mong a list  

y = [1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y)

print(a)

9


<h4 align=left>option (2)

In [27]:
# Also more than one value can be selected  

y = [1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y, size = 5)

print(a)

[9 3 2 9 9]


<h3 align=left>shuffle function

In [28]:
# The shuffle command performs a random change in order  

y = [1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
print(y)

random.shuffle(y)
print(y)

[1, 2, 3, 6, 9, 8, 5, 4, 7, 8, 9, 6, 5, 9, 6]
[3, 4, 9, 5, 9, 6, 1, 8, 8, 6, 5, 9, 2, 6, 7]


<h3 align=left>Matrix of zeros or ones

<h4 align=left>1 D

In [29]:
# •	عمل مصفوفة اصفار او  وحايد  

a = zeros(8)
b = ones(10)

print(a)
print('---------------------------------------------------------------')
print(b)

[0. 0. 0. 0. 0. 0. 0. 0.]
---------------------------------------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


<h4 align=left>2 D

In [30]:
a = zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
b = ones((3,3))

print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<h4 align=left>3 D

In [32]:
# three dimentions

a = zeros((2,3,2))
b = ones((2,3,2))

print(a)
print('---------------------------------------------------------------')
print(b)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
---------------------------------------------------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


<h3 align=left>Identity Matrix

In [33]:
a = eye(5) 
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<h3 align=left>full Matrix

In [34]:
# The full command creates an array with the given number  

a = full((3, 5), 35)
print(a)

[[35 35 35 35 35]
 [35 35 35 35 35]
 [35 35 35 35 35]]


<h3 align=left>range Matrix

In [35]:
# And it is possible to write an array with specific dimensions like this

a =arange(18).reshape(3,6)
b =arange(27).reshape(3,3,3)
'''
where
18 is the range of the numbers
3*6 represent the sahpe of the matrix
important notice: reshape(3*6) = range (18)
'''

print(a)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


<h3 align=left>linspace command

In [36]:
# To write numbers distributed evenly between two numbers using linespace command 

b = linspace(0,30)  # the auto steps are '50' between the required range 
c = linspace(0,100, 5) # i managed the steps to be 5 in this case

print(b)
print('---------------------------------------------------------------')
print(c)

[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
---------------------------------------------------------------
[  0.  25.  50.  75. 100.]


<h3 align=left>lincpace to a Matrix

In [37]:
# •	convert it to a matrix

b =linspace(0,30,12).reshape(3,4)
c =linspace(0,100,27).reshape(3,3,3)

print('b = \n', b)
print('---------------------------------------------------------------')
print('c = \n', c)

b = 
 [[ 0.          2.72727273  5.45454545  8.18181818]
 [10.90909091 13.63636364 16.36363636 19.09090909]
 [21.81818182 24.54545455 27.27272727 30.        ]]
---------------------------------------------------------------
c = 
 [[[  0.           3.84615385   7.69230769]
  [ 11.53846154  15.38461538  19.23076923]
  [ 23.07692308  26.92307692  30.76923077]]

 [[ 34.61538462  38.46153846  42.30769231]
  [ 46.15384615  50.          53.84615385]
  [ 57.69230769  61.53846154  65.38461538]]

 [[ 69.23076923  73.07692308  76.92307692]
  [ 80.76923077  84.61538462  88.46153846]
  [ 92.30769231  96.15384615 100.        ]]]


<h3 align=left>Diagonal Matrix

In [38]:
a =diag(array([5,12,4,-1,3]))

b =diag(array([5,12,4,-1,3]),k=3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')

[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
-------------------------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
-------------------------


<h3 align=left>Dealing with Matrices

In [39]:
# Numbers that are not zero can be calculated using count_nonzero command


a = random.randint(0, 10, (3, 3))
print(a)

[[2 9 2]
 [0 5 1]
 [9 3 0]]


In [40]:
b = count_nonzero(a)
print(b)

7


In [41]:
# Or specify the number of numbers greater or less than a certain value

c = count_nonzero(a>5)
d = count_nonzero(a<7)

print(c)
print('---------------------------------------------------------------')
print(d)

2
---------------------------------------------------------------
7


In [42]:
# deal with each raw then gives a sum value per each.

b = count_nonzero(a>5,axis=1)   
c = count_nonzero(a<8,axis=1)

print('a =', a)
print('-------------------------')
print('b =', b)
print('-------------------------')
print('c =', c)

a = [[2 9 2]
 [0 5 1]
 [9 3 0]]
-------------------------
b = [1 0 1]
-------------------------
c = [2 3 2]


In [43]:
# To find out whether there is a number greater or less than a certain value or not

b = any(a>5)
print(a)
print('-------------------------')
print(b)

[[2 9 2]
 [0 5 1]
 [9 3 0]]
-------------------------
True


In [44]:
# It can be done in every row 

b = any(a>5,axis=1)

print(a)
print('-------------------------')
print(b)

[[2 9 2]
 [0 5 1]
 [9 3 0]]
-------------------------
[ True False  True]


In [45]:
# It is possible to find out whether all elements are complying with a certain condition

b = all(a>5)

print(a)
print('-------------------------')
print(b)

[[2 9 2]
 [0 5 1]
 [9 3 0]]
-------------------------
False


In [46]:
# You can find out if the elements are greater than or less than a certain number

a =random.randint(5,20, size=9).reshape(3,3)

b = a>10
c = a<15

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[12  5 10]
 [ 6 18 15]
 [13  8 11]]
-------------------------
[[ True False False]
 [False  True  True]
 [ True False  True]]
-------------------------
[[ True  True  True]
 [ True False False]
 [ True  True  True]]


<h3 align=left>Compare between Matrices

In [47]:
# isclose command

a =arange(9).reshape(3,3)
b =arange(9).reshape(3,3)
c = 2*b
d = isclose(a,b,rtol = 0.1)
e = isclose(a,c,rtol = 0.1)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
-------------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------------------------
[[ True False False]
 [False False False]
 [False False False]]


<h3 align=left>Matrix multiplication

In [48]:
# Matrix values can be multiplied by a number
 
a =arange(5)
b =empty(5)

multiply(a, 10, out=b)

print(a)
print('-------------------------')
print(b)

[0 1 2 3 4]
-------------------------
[ 0. 10. 20. 30. 40.]


In [49]:
# To raise all elements to the a chosen power  

power(a, 4, out=b)

print(a)
print('-------------------------')
print(b)

[0 1 2 3 4]
-------------------------
[  0.   1.  16.  81. 256.]


<h3 align=left>matrix summation value

In [50]:
# The sum of the matrix values and reduce the matrix dimensions 

a = arange(15)
b = add.reduce(a)

print(a)
print('-------------------------')
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------------------
105


In [51]:
# The product of the matrix values 

a =arange(2,8)
b = multiply.reduce(a)

print(a)
print('-------------------------')
print(b)

[2 3 4 5 6 7]
-------------------------
5040


In [52]:
'''
Reciprocal multiplication: where it takes the first numner then multiply it in all the list,
for the second raw it takes the second number of the list then multiply it on all the list,
and so on till it useses all the list numbers   
'''
a =arange(2,8)
b = multiply.outer(a,a)

print('a =', a)
print('-------------------------')
print('b =', b)

a = [2 3 4 5 6 7]
-------------------------
b = [[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


In [53]:
# Add all previous numbers:   

a =arange(10)
b = add.accumulate(a)

print(a)
print('-------------------------')
print(b)

[0 1 2 3 4 5 6 7 8 9]
-------------------------
[ 0  1  3  6 10 15 21 28 36 45]


In [54]:
# Multiply the previous numbers  
 
a =arange(2,8)
b = multiply.accumulate(a)

print(a)
print('-------------------------')
print(b)

[2 3 4 5 6 7]
-------------------------
[   2    6   24  120  720 5040]


<h3 align=left>matrix length

In [55]:
# To find out the number of elements of the array, or the number of its rows, if more than one.
 
a =arange(12)
b = len(a)

print(a)
print('-------------------------')
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
12


In [56]:
c = a.reshape(3,4)
d = len(c)

print('c value =', c)
print('-------------------------')
print('d value =', d, 'raws in the matrix') # number of raws

c value = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
d value = 3 raws in the matrix


In [57]:
# To find out all the number of its elements 
 
b = size(a)
print(b)

12


In [58]:
c = a.reshape(3,4)
d = c.size  # will give all the number of the elements inside the matrix

print('c value =', c)
print('-------------------------')
print('d value =', d)

c value = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
d value = 12


In [59]:
# Here are the dimensions in detail
 
a =arange(12)
b = a.shape

c = a.reshape(3,4)
d = c.shape

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
(12,)
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
(3, 4)


<h3 align=left>Matrix Dimension

In [60]:
# Dimensions number
 
a =arange(12)
b = a.ndim

c = a.reshape(3,4)
d = c.ndim

print(a)
print('-------------------------')
print('no.of the matrix dimentions =', b)
print('-------------------------')
print(c)
print('-------------------------')
print('no.of the matrix dimentions =',d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
no.of the matrix dimentions = 1
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
no.of the matrix dimentions = 2


<h3 align=left>data type inside the Matrix

In [61]:
a =array(['a','d','g','h','j'])
b = a.dtype

c = arange(12)
d = c.reshape(3,4)
e = d.dtype

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

['a' 'd' 'g' 'h' 'j']
-------------------------
<U1
-------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
int32


<h3 align =left>The sum of the matrix diagonal

In [62]:
# sum of the matrix diagonal using trace command

a =arange(9)
b = a.reshape(3,3)
c = trace(b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[0 1 2 3 4 5 6 7 8]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
12


In [63]:
# The determinant value of the matrix, and the Egan Value

a =arange(9).reshape(3,3)

c = linalg.det(a) # matrix determinant
d = linalg.eig(a) # Compute the eigenvalues and right eigenvectors of a square array.
print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
0.0
-------------------------
(array([ 1.33484692e+01, -1.34846923e+00, -1.26963291e-15]), array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


<h3 align=left>Subtraction From The Matrix

In [64]:
# Subtraction from an array

a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[0 1 2 3 4 5 6 7 8 9]
-------------------------
3
-------------------------
[3 4 5 6 7 8]
-------------------------
[3 5 7]
-------------------------
9
-------------------------
7


In [65]:
# Subtraction from a 2D matrix.


a =arange(36).reshape(6,6)

c = a[3]         # pick raw no. 4
d = a[3:9]       # pick from raw no. 4 to the last raw
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
-------------------------
[30 31 32 33 34 35]
-------------------------
[18 19 20 21 22 23]


In [66]:
a =arange(36).reshape(6,6)

c = a[3,1]
d = a[3,:]
e = a[:,2]
f = a[:,1:3]
g = a[1:2,:]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
19
-------------------------
[18 19 20 21 22 23]
-------------------------
[ 2  8 14 20 26 32]
-------------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
-------------------------
[[ 6  7  8  9 10 11]]


In [67]:
a =arange(36).reshape(6,6)

c = a[3:4,1:5]
d = a[2:,3:]
e = a[:2,:3]
f = a[:,-1]
g = a[-1,:]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[19 20 21 22]]
-------------------------
[[15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
-------------------------
[[0 1 2]
 [6 7 8]]
-------------------------
[ 5 11 17 23 29 35]
-------------------------
[30 31 32 33 34 35]


In [68]:
a =arange(36).reshape(6,6)

c = a[::2,::3]
d = a[::-1,::-1] # this will reverse the matrix
e = a[:2:-1,:3:-1]
f = a[2::2,3::3]
g = a[-1::,-1::]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[ 0  3]
 [12 15]
 [24 27]]
-------------------------
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
-------------------------
[[35 34]
 [29 28]
 [23 22]]
-------------------------
[[15]
 [27]]
-------------------------
[[35]]


In [69]:
# 3D  

a =arange(18).reshape(3,3,2)

c = a[1]  # pick the second layer
d = a[1,2]
e = a[2,2,1]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
-------------------------
[[ 6  7]
 [ 8  9]
 [10 11]]
-------------------------
[10 11]
-------------------------
17


<h3 align=left>Modify Values

In [70]:
a =arange(16).reshape(4,4)

print(a)
print('-------------------------')
a[2,3] = 0
print(a)
print('-------------------------')
a[:,3] = 0 
print(a)
print('-------------------------')
a[2,:] = 0 
print(a)
print('-------------------------')
a[:,:] = 0 
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]
-------------------------
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]]
-------------------------
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 0  0  0  0]
 [12 13 14  0]]
-------------------------
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


<h3 align=left>Dealing with copied matrices 

In [71]:
'''
The copied matrices is affected with any operations have been done in the original one, as the following example 
'''

a =arange(16).reshape(4,4)


print(a)
print('-------------------------')
b = a[:,1:3]
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-------------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [72]:
a[:,:] = 5
print(a)
print('-------------------------')
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-------------------------
[[5 5]
 [5 5]
 [5 5]
 [5 5]]


<h3 align=left>Independent Matrices 

In [73]:
a =arange(16).reshape(4,4)
print(a)
print('-------------------------')
b = a[:,1:3].copy()                   # this copy will not be affect with any operation in the main matrix
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-------------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [74]:
print('-------------------------')
a[:,:] = 5
print(a)
print('-------------------------')
print(b)

-------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-------------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


<h3 align=left>Split command

In [75]:
x = [11,22,33,44,55,66,77,88]

x1, x2, x3 = split(x, (3,6))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (1,5))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (6, 3))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (0, 3))
print(x1, x2, x3)
print('-------------------------')
x1, x2, x3 = split(x, (4, 0))
print(x1, x2, x3)

[11 22 33] [44 55 66] [77 88]
-------------------------
[11] [22 33 44 55] [66 77 88]
-------------------------
[11 22 33 44 55 66] [] [44 55 66 77 88]
-------------------------
[] [11 22 33] [44 55 66 77 88]
-------------------------
[11 22 33 44] [] [11 22 33 44 55 66 77 88]


<h3 align=left>Select an Item form the matrix

In [76]:
a =arange(16).reshape(4,4)

b = a[2][1]

print(a)
print('-------------------------')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-------------------------
9


<h3 align=left>Combine Matrices

<h4 align=left>stack command

In [77]:
# vertical stack

a =arange(4).reshape(2,2)
b =2*arange(4).reshape(2,2)

c = vstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [78]:
# horizontal stack

a =arange(4).reshape(2,2)
b =2*a

c = hstack((a,b))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[0 1]
 [2 3]]
-------------------------
[[0 2]
 [4 6]]
-------------------------
[[0 1 0 2]
 [2 3 4 6]]


<h4 align=left>Concatenate command

In [79]:
# Vertical concatenation

a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b] , axis = 0)   # same as vstack

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

[[19 16  6]
 [11  7 10]
 [11 18 19]]
-------------------------
[[ 6 17 18]
 [ 6 13  9]
 [18  5 17]]
-------------------------
[[19 16  6]
 [11  7 10]
 [11 18 19]
 [ 6 17 18]
 [ 6 13  9]
 [18  5 17]]
-------------------------


In [80]:
# horizontal concatenation   

c = concatenate([a,b] , axis = 1)
print(c)

[[19 16  6  6 17 18]
 [11  7 10  6 13  9]
 [11 18 19 18  5 17]]


In [81]:
#  Detect the largest and smallest values in a matrix  

a = random.randint(5,20, size=9).reshape(3,3)

b = a.max()
c = a.min()
d = a.argmax()  # detect the place of the maximum value inside the matrix
e = a.argmin() # detect the place of the minimum value inside the matrix

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[14 10  6]
 [16 16  9]
 [18 11 16]]
-------------------------
18
-------------------------
6
-------------------------
6
-------------------------
2


<h3 align=left>Find the Matrix Variance and the Covariance 

In [82]:
a =random.randint(5,20, size=9).reshape(3,3)

b = var(a)
c = cov(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[12  6 19]
 [ 7 10 16]
 [ 5  7 11]]
-------------------------
20.0
-------------------------
[[42.33333333 20.5        13.66666667]
 [20.5        21.         14.        ]
 [13.66666667 14.          9.33333333]]


<h3 align=left>Mathematical Operations for Matrices

<h4 align=left>Addition and Subtraction  

In [83]:
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)

c = a+b
d = a-b

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[[10 15  5]
 [ 7 11  7]
 [12 17 15]]
-------------------------
[[ 9 12  9]
 [14 15  6]
 [13 19 18]]
-------------------------
[[19 27 14]
 [21 26 13]
 [25 36 33]]
-------------------------
[[ 1  3 -4]
 [-7 -4  1]
 [-1 -2 -3]]


<h4 align=left>Multiplication and division

In [84]:
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)

c = a*b # direct multiply number by number
d = a/b

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[[13  9 18]
 [11  5 14]
 [17 13 18]]
-------------------------
[[ 6 19 19]
 [16  7  6]
 [15  8 14]]
-------------------------
[[ 78 171 342]
 [176  35  84]
 [255 104 252]]
-------------------------
[[2.16666667 0.47368421 0.94736842]
 [0.6875     0.71428571 2.33333333]
 [1.13333333 1.625      1.28571429]]


<h4 align=left>Multiplication and division by a number

In [85]:
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a*3
d = b/5

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[[16  7 15]
 [ 7  8  6]
 [19 16 17]]
-------------------------
[[14 17 11]
 [14 15 19]
 [17 15  7]]
-------------------------
[[48 21 45]
 [21 24 18]
 [57 48 51]]
-------------------------
[[2.8 3.4 2.2]
 [2.8 3.  3.8]
 [3.4 3.  1.4]]


<h4 align=left>functions of the matrix

In [86]:
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)

c = sin(a)
d = b**2
e = log(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[ 7 18 16]
 [18 12 18]
 [ 5 16 19]]
-------------------------
[[12 10 18]
 [ 8 16 17]
 [13 13  5]]
-------------------------
[[ 0.6569866  -0.75098725 -0.28790332]
 [-0.75098725 -0.53657292 -0.75098725]
 [-0.95892427 -0.28790332  0.14987721]]
-------------------------
[[144 100 324]
 [ 64 256 289]
 [169 169  25]]
-------------------------
[[1.94591015 2.89037176 2.77258872]
 [2.89037176 2.48490665 2.89037176]
 [1.60943791 2.77258872 2.94443898]]


<h4 align=left>Multiply the Matrices

In [87]:
a =random.randint(1,4, size=9).reshape(3,3)
b =random.randint(1,4, size=9).reshape(3,3)

c = dot(a,b) 

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[1 3 3]
 [2 2 2]
 [1 1 2]]
-------------------------
[[1 3 3]
 [3 3 1]
 [3 1 1]]
-------------------------
[[19 15  9]
 [14 14 10]
 [10  8  6]]


<h4 align=left>Matrix Summation

In [88]:
a =random.randint(5,20, size=9).reshape(3,3)
b = sum(a)
c = a.sum()
d = a.sum(axis = 1)  # individually sum each raw 
e = a.sum(axis = 0)  # individually sum each column

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[[ 5  7 19]
 [ 6  9  5]
 [14 16 12]]
-------------------------
93
-------------------------
93
-------------------------
[31 20 42]
-------------------------
[25 32 36]


<h4 align=left>Statistical Values

In [89]:
a =random.randint(5,20, size=9).reshape(3,3)
b = a.mean()
c = a.std()
d = a.var()

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

[[15  8 16]
 [10  5 14]
 [12 12 13]]
-------------------------
11.666666666666666
-------------------------
3.299831645537222
-------------------------
10.888888888888891


<h4 align=left>Correlation Coefficient

In [90]:
 

a =random.randint(5,20, size=9).reshape(3,3)
b = corrcoef(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')

[[15 10 12]
 [18  5 18]
 [ 8 17 13]]
-------------------------
[[ 1.          0.80295507 -0.99870494]
 [ 0.80295507  1.         -0.83223972]
 [-0.99870494 -0.83223972  1.        ]]
-------------------------


<h4 align=left>Matrix sort

In [91]:
a =random.randint(5,20, size=9).reshape(3,3)
b = sort(a,axis=0)  # sort columns
c = sort(a,axis=1)  # sort raws

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')

[[ 6  6  9]
 [14 18  6]
 [ 9 16  7]]
-------------------------
[[ 6  6  6]
 [ 9 16  7]
 [14 18  9]]
-------------------------
[[ 6  6  9]
 [ 6 14 18]
 [ 7  9 16]]
-------------------------


<h4 align=left>Matrix Inversion

In [92]:
a =random.randint(1,4, size=9).reshape(3,3)
b =linalg.inv(a)   # matrix inverse


'''
when you multiply the matrix with its inversion you got the identity matrix
'''
c = dot(a,b)       
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)

[[2 3 1]
 [2 3 3]
 [1 2 2]]
-------------------------
[[ 0.   2.  -3. ]
 [ 0.5 -1.5  2. ]
 [-0.5  0.5  0. ]]
-------------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h2 align=left> Read files

<h3 align=left>Load and read the files

<h4 align=left>Example (1):

In [93]:
fname = 'data_1.txt'
dtype1 = dtype([('gender', '|S1'), ('height', 'f4')])
a = loadtxt(fname, dtype = dtype1, skiprows = 9, usecols = (1, 3))

print(a)

[(b'M', 1.82) (b'M', 1.77) (b'F', 1.68) (b'M', 1.72) (b'F', 1.78)
 (b'F', 1.6 ) (b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64)
 (b'M', 1.63) (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 )
 (b'M', 1.97) (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]


<h4 align=left>Example (2):

In [94]:
a, b, c = loadtxt('data_2.txt', unpack = True,skiprows = 3)

print('a =', a)
print('b =', b)
print('c =', c)

a = [1890. 1900. 1910. 1920. 1930.]
b = [26.1 25.9 25.1 24.6 24.3]
c = [22.  21.9 21.6 21.2 21.3]


<h4 align=left>Example (3):

In [95]:
data = genfromtxt('data_3.txt',
                  skip_header=1,
                  dtype=[('student', 'u8'), ('gender', 'S1'), ('black', 'f8'),
                         ('colour', 'f8')],
                  delimiter = ',',
                  missing_values = 'X')

print(data)

[(1, b'F', 18.72, 31.11) (2, b'F', 21.14, 52.47) (3, b'F', 19.38, 33.9 )]


<h2 align=left>Polynomials

<h3 align=left>polyfit command

In [96]:
X = array([0, 20, 40, 60, 80, 100, 120, 140, 160, 180])
Y = array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

# to get the best fit

points = polyfit(X, Y, 1) # (1) refer A polynomial of degree 1, which is a linear expression.

'''
the output has two numbers which represents the best line where, 
the the first number is the slope and the second one is the intersect
'''

print('points = ', points)

points =  [-0.05 10.  ]


In [97]:
x = array([3, 6, 2, 5, 4])
y = array([2, 3, -9, 6, 2.5])

z = polyfit(x, y, 1)  # best fit

print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)
print('-------------------------')

[3 6 2 5 4]
-------------------------
[ 2.   3.  -9.   6.   2.5]
-------------------------
[  2.8 -10.3]
-------------------------


<h3 align=left>Get the Polynomial Equation 

In [98]:
a = poly1d((-7))                   # just constant
b = poly1d((-7, 2))                # linear equation
c = poly1d((-7, 2, 1))             # quadratic equation
d = poly1d((-7, 2, 1, 3))
e = poly1d((-7, 2, 1, 3, 6))

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
-------------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6


<h3 align=left>Compansate The Value of "x"

<h4 align=left>Option (1):

In [99]:
a = poly1d((-7, 2, 1, 3, 6))

b = a(5)
c = a(0)
d = a(-15)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
-------------------------
-4079
-------------------------
6
-------------------------
-360939


<h4 align=left>Option (2):

In [100]:
# •	أمر مختلف

a = polyval((1, 2), 2)               # linear equation and compansate X with value of 2.
b = polyval((1, 2, 3), 7)            # quadratic equation and compansate X with value of 7.
c = polyval((1, 2, 3, 5), -3)
d = polyval((1, 2, 3, 5, -6), 12.6)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)

4
-------------------------
66
-------------------------
-13
-------------------------
29738.769599999992


<h3 align=left>Derivative

<h4 align=left>polyder command

In [102]:
a = polyder(poly1d((1, 2, 3)))          # first derivitave
b = polyder(poly1d((1, 2, 3)), 2)        # second derivitave
c = polyder(poly1d((1, 2, 3)), 3)        # third derivitave

d = polyder(poly1d((1, 2, 3, 5, 12)))     # first derivitave
e = polyder(poly1d((1, 2, 3, 5, 12)), 3)   # third derivitave

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

 
2 x + 2
-------------------------
 
2
-------------------------
 
0
-------------------------
   3     2
4 x + 6 x + 6 x + 5
-------------------------
 
24 x + 12


<h4 align=left>Compansate the value of "x"

In [103]:
a = polyder(poly1d((1, 2, 3)))
b = polyder(poly1d((1, 2, 3)), 2)
c = polyder(poly1d((1, 2, 3)), 3)

d = polyder(poly1d((1, 2, 3, 5, 12)))
e = polyder(poly1d((1, 2, 3, 5, 12)), 3)

print(a(2))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))

6
-------------------------
2
-------------------------
0
-------------------------
1
-------------------------
132


<h3 align=left>Integration

<h4 align=left>polyint command

In [104]:
a = polyint(poly1d((1, 2, 3)))
b = polyint(poly1d((1, 2, 3)), 2)
c = polyint(poly1d((1, 2, 3)), 3)

d = polyint(poly1d((1, 2, 3, 5, 12)))
e = polyint(poly1d((1, 2, 3, 5, 12)), 3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
-------------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 2.5 x + 12 x
-------------------------
          7           6        5          4     3
0.004762 x + 0.01667 x + 0.05 x + 0.2083 x + 2 x


<h4 align=left>Compansate the Value of "x"

In [105]:
a = polyint(poly1d((1, 2, 3)))
b = polyint(poly1d((1, 2, 3)), 2)
c = polyint(poly1d((1, 2, 3)), 3)

d = polyint(poly1d((1, 2, 3, 5, 12)))
e = polyint(poly1d((1, 2, 3, 5, 12)), 3)

print(a(2))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))

12.666666666666666
-------------------------
0.0
-------------------------
24.300000000000004
-------------------------
-10.2
-------------------------
1168.8988095238094


<h3 align=left>Roots of the Equation

In [106]:
# the values when you compansate it in the equation the output will be zero.

a = roots(poly1d((1, 2)))
b = roots(poly1d((1, 2, 3)))
c = roots(poly1d((1, 2, 3, 5)))
d = roots(poly1d((1, 2, 3, 5, 12)))
e = roots(poly1d((1, 2, 3, 5, 12, 22)))

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)

[-2.]
-------------------------
[-1.+1.41421356j -1.-1.41421356j]
-------------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
-------------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
-------------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]


<h2 align=left>Deal with time

<h3 align=left>Datetime64 command

In [107]:
x = array('2021-08-13', dtype=datetime64)
print(x)

2021-08-13


In [108]:
x = datetime64('2021-08-14')
print(x)

2021-08-14


<h3 align=left>Days Increase

In [109]:
x = datetime64('2021-02-26')

y = x + arange(12)

print(x)
print('-------------------------')
print(y)

2021-02-26
-------------------------
['2021-02-26' '2021-02-27' '2021-02-28' '2021-03-01' '2021-03-02'
 '2021-03-03' '2021-03-04' '2021-03-05' '2021-03-06' '2021-03-07'
 '2021-03-08' '2021-03-09']


<h3 align=left>Days Decrease

In [110]:
x = datetime64('2015-07-04')

y = x - arange(12)

print(x)
print('-------------------------')
print(y)

2015-07-04
-------------------------
['2015-07-04' '2015-07-03' '2015-07-02' '2015-07-01' '2015-06-30'
 '2015-06-29' '2015-06-28' '2015-06-27' '2015-06-26' '2015-06-25'
 '2015-06-24' '2015-06-23']


<h3 align=left>Days Difference

In [111]:
x = datetime64('1975-04-20')
y = datetime64('2022-12-29')

z = y-x

print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)

1975-04-20
-------------------------
2022-12-29
-------------------------
17420 days


<h2 align=left>functions in numpy

In [112]:
# They are used with the fromfunction command

x = fromfunction(lambda i: i**3, (10, ))

print(x)

[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]


In [113]:
# 1 Dimension

x = fromfunction(lambda i: 3 * (i + 5)**3, (10, ))
print(x)

[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]


In [114]:
# 2 Dimensions

x = fromfunction(lambda i, j: i + j, (4, 5))
'''
python puts i as a column, for first column it adds the first value of j,
second column adds the second value of j and so on
'''

print(x)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]


In [115]:
x = fromfunction(lambda i, j: 3 * i * j, (4, 5))
print(x)

[[ 0.  0.  0.  0.  0.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  6. 12. 18. 24.]
 [ 0.  9. 18. 27. 36.]]


In [116]:
# 3 Dimensions

x = fromfunction(lambda i, j, k: i + j + k, (2, 3, 4))
print(x)

[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]


In [117]:
x = fromfunction(lambda i, j, k: (2 * i) + (j**2) * k, (2, 3, 4))
print(x)

[[[ 0.  0.  0.  0.]
  [ 0.  1.  2.  3.]
  [ 0.  4.  8. 12.]]

 [[ 2.  2.  2.  2.]
  [ 2.  3.  4.  5.]
  [ 2.  6. 10. 14.]]]


In [118]:
def powers(i):
    i = i**2
    return i


x = fromfunction(powers, (9, ), dtype=int)
print(x)

[ 0  1  4  9 16 25 36 49 64]


In [119]:
def powers(i, j):
    i = i**j
    return i


x = fromfunction(powers, (4, 5), dtype=int)
# N.B: 0**0 does not equal 1, put python type it as one 
print(x)

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]


In [120]:
# Boolean values

m, n = 20, 5


def f(i):
    return (i % n == 0)


x = fromfunction(f, (m, ))
print(x)

[ True False False False False  True False False False False  True False
 False False False  True False False False False]
